### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by ghost** [travs/icon-font-picker#4] opened 2015-05-10 06:37 UTC
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.

```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:57:13)
Object.activate (/Users/varden/.atom/packages/icon-font-picker/lib/icon-font-picker.js:22:20)
Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:242:19)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:223:30)
```

**Comment by hebbet** [comment] 2015-05-11 06:08
Duplicate of #2

**Comment by travs** [comment] 2015-05-11 15:31
@vardenn Are these being generated automatically or something?

**Closed as completed** 2015-05-11 15:31 UTC

**Comment by hebbet** [comment] 2015-05-28 15:13
@travs atom added a report issue button in the deprecations cop.
